export const dataTable = {
  colums: [
    {
      title: "STT",
      dataIndex: "key",
      key: "key",
    },
    {
      title: "Mã yêu cầu",
      dataIndex: "requestCode",
      key: "requestCode",
      scopedSlots: { customRender: "requestCode" },
    },
    {
      title: "Loại yêu cầu",
      dataIndex: "requestType",
      key: "requestType",
    },
    {
      title: "Dịch vụ",
      dataIndex: "service",
      key: "service",
    },
    {
      title: "Loại giao dịch",
      dataIndex: "transactionType",
      key: "transactionType",
    },
    {
      title: "Lĩnh vực kinh doanh",
      dataIndex: "businessField",
      key: "businessField",
    },
    {
      title: "Người yêu cầu",
      dataIndex: "requester",
      key: "requester",
    },
    {
      title: "Thời gian yêu cầu",
      dataIndex: "requestTime",
      key: "requestTime",
    },
    {
      title: "Người duyệt",
      dataIndex: "reviewer",
      key: "reviewer",
    },
    {
      title: "Thời gian duyệt",
      dataIndex: "browsingTime",
      key: "browsingTime",
    },
    {
      title: "Trạng thái yêu cầu",
      dataIndex: "requestStatus",
      key: "requestStatus",
    },
    {
      title: "Thao tác",
      dataIndex: "operation",
      key: "operation",
      scopedSlots: { customRender: "operation" },
    },
  ],
  dataColumns: [
    {
      key: "1",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ chi hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Trần Ngọc Bích",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Trần Ngọc Bích",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Chờ duyệt",
    },
    {
      key: "2",
      requestCode: 201,
      requestType: "Cập nhập trạng thái giao dịch,hạch toán",
      service: "Hỗ trợ thu hộ",
      transactionType: "Chuyển tiền",
      businessField: "Thu hộ tiền COD",
      requester: "Trần Ngọc Bích",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Trần Ngọc Bích",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Từ chối",
    },
    {
      key: "3",
      requestCode: 403,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ chi hộ",
      transactionType: "Hoàn",
      businessField: "Chi tiền BTXH",
      requester: "Trần Ngọc Bích",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Trần Ngọc Bích",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
    },
    {
      key: "4",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Hủy",
      businessField: "Thanh toán qua QR",
      requester: "Trần Ngọc Bích",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Chờ duyệt",
    },
    {
      key: "5",
      requestCode: 303,
      requestType: "Cập nhập trạng thái GD",
      service: "Hỗ trợ chi hộ",
      transactionType: "Thu khác",
      businessField: "Chi tiền BTXH",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Chờ duyệt",
    },
    {
      key: "6",
      requestCode: 200,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Chuyển tiền",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Chờ duyệt",
    },
    {
      key: "7",
      requestCode: 401,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Chờ duyệt",
      //   operation: "Duyệt ",
    },
    {
      key: "8",
      requestCode: 404,
      requestType: "Cập nhập trạng thái GD",
      service: "Hỗ trợ thu hộ",
      transactionType: "Hoàn",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "9",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "10",
      requestCode: 404,
      requestType: "Cập nhập trạng thái GD",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "11",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "12",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "13",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "14",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "15",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "16",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Lưu Công Bảo Long",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Lưu Công Bảo Long",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "17",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "18",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "19",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "20",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "21",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "22",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "23",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "24",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Nguyễn Thị Thúy Hằng",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Nguyễn Thị Thúy Hằng",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "25",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Nguyễn Thị Thúy Hằng",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Nguyễn Thị Thúy Hằng",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "26",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "27",
      requestCode: 304,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "28",
      requestCode: 201,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "29",
      requestCode: 201,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "30",
      requestCode: 303,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "31",
      requestCode: 403,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "32",
      requestCode: 404,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Trang",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Trang",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "33",
      requestCode: 204,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "34",
      requestCode: 401,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "35",
      requestCode: 505,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "36",
      requestCode: 504,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "37",
      requestCode: 303,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "38",
      requestCode: 403,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến Nhi",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến Nhi",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "39",
      requestCode: 201,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Vũ Đức Toàn",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Vũ Đức Toàn",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
    {
      key: "40",
      requestCode: 503,
      requestType: "Insert giao dịch",
      service: "Hỗ trợ thu hộ",
      transactionType: "Thanh toán",
      businessField: "Thanh toán qua QR",
      requester: "Phan Thị Yến",
      requestTime: "2014-12-24 23:12:00",
      reviewer: "Phan Thị Yến",
      browsingTime: "2014-12-26 23:12:00",
      requestStatus: "Đã duyệt",
      //   operation: "Xem",
    },
  ],
};

export const dataColumns1 = (pagination) => [
  {
    title: "STT",
    // dataIndex: "id",
    // key: "id",
    // align: "center",
    customRender: (text, record, index) => {
      return (pagination.current - 1) * pagination.pageSize + index + 1;
    },
  },
  {
    title: "Mã giao dịch core PPC",
    dataIndex: "transactionCode",
    key: "transactionCode",
    align: "center",
  },
  {
    title: "Số tiền giao dịch (đ)",
    dataIndex: "transactionAmount",
    key: "transactionAmount",
    align: "center",
  },
  {
    title: "Thời gian giao dịch",
    dataIndex: "transactionTime",
    key: "transactionTime",
  },
  {
    title: "Trạng thái giao dịch",
    dataIndex: "transactionStatus",
    key: "transactionStatus",
  },
  {
    title: "Trạng thái cập nhật",
    dataIndex: "updatedStatus",
    key: "updatedStatus",
  },
  {
    title: "Lý do cập nhật",
    dataIndex: "updateReason",
    key: "updateReason",
  },
];
export const dataColumns2 = (pagination) => [
  {
    title: "STT",
    // dataIndex: "id",
    // key: "id",
    customRender: (text, record, index) => {
      return (pagination.current - 1) * pagination.pageSize + index + 1;
    },
  },
  {
    title: "Mã tham chiếu",
    dataIndex: "referenceCode",
    key: "referenceCode",
  },
  {
    title: "Số tiền giao dịch",
    dataIndex: "transactionAmount",
    key: "transactionAmount",
    align: "right",
  },
  {
    title: "Phí",
    dataIndex: "fee",
    key: "fee",
  },
  {
    title: "Thuế",
    dataIndex: "tax",
    key: "tax",
  },
  {
    title: "Mã giao dịch tại ngân hàng",
    dataIndex: "transactionBank",
    key: "transactionBank",
  },
  {
    title: "Thời gian giao dịch",
    dataIndex: "transactionTime",
    key: "transactionTime",
  },
  {
    title: "Mã giao dịch Napas",
    dataIndex: "transactionNapas",
    key: "transactionNapas",
  },
  {
    title: "NapasTraceid",
    dataIndex: "napasTraceid",
    key: "napasTraceid",
  },
  {
    title: "Tên tài khoản chuyển",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Lý do",
    dataIndex: "reason",
    key: "reason",
  },
];
